server:
  port: 8888
spring:
  application:
    name: gateway
  cloud:
    nacos:
      server-addr: http://47.94.206.220:8848
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: manage-service # 路由规则id，自定义，唯一
          uri: lb://manage-service # 路由的目标服务，lb代表负载均衡，会从注册中心拉取服务列表
          predicates: # 路由断言，判断当前请求是否符合当前规则，符合则路由到目标服务
            - Path=/admin/** # 这里是以请求路径作为判断规则
        - id: teach-service
          uri: lb://teach-service
          predicates:
            - Path=/api/students/**,/api/teachers/**,/api/assistants/**
        - id: user-center-service
          uri: lb://user-center-service
          predicates:
            - Path=/users/**,/login/**,/logout/**
        - id: blog-service
          uri: lb://blog-service
          predicates:
            - Path=/articles/**,/categorys/**,/comments/**,/favorites/**,/messages/**,/tags/**,/upload/**
      globalcors: # 全局跨域配置
        add-to-simple-url-handler-mapping: true # 解决options请求被拦截问题
        cors-configurations:
          '[/**]': # 匹配请求
            allowedOrigins: "http://frontend,http://47.94.206.220:30080"
            allowCredentials: true # 是否允许携带cookie
            allowedMethods: "*" # 支持的方法
            allowedHeaders: "*" # 允许在请求中携带的头信息
logging:
  level:
    com.example.filter.LoggingFilter: INFO