server:
  port: 8888
spring:
  application:
    name: gateway
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
    gateway:
      routes:
        - id: manage-service # 路由规则id，自定义，唯一
          uri: lb://manage-service # 路由的目标服务，lb代表负载均衡，会从注册中心拉取服务列表
          predicates: # 路由断言，判断当前请求是否符合当前规则，符合则路由到目标服务
            - Path=/admin/** # 这里是以请求路径作为判断规则


        - id: teach-service
          uri: lb://teach-service
          predicates:
            - Path=/api/students/**
            - Path=/api/teachers/**
            - Path=/api/assistants/**
            - Path=/api/upload/**

        - id: user-center-service
          uri: lb://user-center-service
          predicates:
            - Path=/users/**
            - Path=/login/**

        - id: blog-service
          uri: lb://blog-service
          predicates:
            - Path=/articles/**
            - Path=/categorys/**
            - Path=/comments/**
            - Path=/favorites/**
            - Path=/messages/**
            - Path=/tags/**
            - Path=/upload/**

      globalcors: # 全局跨域配置
        add-to-simple-url-handler-mapping: true # 解决options请求被拦截问题
        cors-configurations: # 跨域配置列表
          '[/**]': # 匹配所有路径
            allowed-headers: "*" # 允许的请求头，*表示允许所有
            allowed-methods: # 允许的请求方法列表
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS

            allowed-origins:
              - http://localhost:5173
            exposed-headers: "*"
            allow-credentials: true # 是否允许凭证传递，true表示允许
            maxAge: 36000