apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: aintme/summer-term-mysql:latest
        imagePullPolicy: Never
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "123456"
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
        # resources:
        #   limits:
        #     cpu: "1000m"  # 限制 CPU 使用量
        #     memory: "1024Mi"  # 限制内存使用量
        #   requests:
        #     cpu: "500m"  # 请求的 CPU 使用量
        #     memory: "512Mi"  # 请求的内存使用量
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pvc  # 这里引用 PVC
