apiVersion: v1  # Kubernetes API 版本
kind: Service  # 资源类型，表示这是一个 Service 对象
metadata:
  name: blog-service  # Service 的名字
spec:
  ports:
  - port: 9888  # Service 公开的端口
    targetPort: 9888  # 转发到容器的端口
  selector:
    app: blog-service  # Service 选择的 Pod 的标签
