# 定义 MySQL 的 Deployment，用于管理 MySQL 容器的创建和更新
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql  # Deployment 的名称
  namespace: my-application  # 指定资源所在的命名空间
spec:
  selector:
    matchLabels:
      app: mysql  # 选择带有此标签的 Pod，确保服务与 Deployment 匹配
  replicas: 1  # 运行的 Pod 副本数量，这里设为1，表示只运行一个 MySQL 实例
  template:
    metadata:
      labels:
        app: mysql  # Pod 的标签，必须与服务的 selector 匹配
    spec:
      containers:
      - name: mysql  # 容器的名称
        image: mysql:8.0  # 使用的 MySQL 镜像版本
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: summerTerm  # 设置 MySQL 的 root 用户密码
        - name: MYSQL_DATABASE
          value: summerTerm  # 初始化时创建的数据库名称
        - name: MYSQL_USER
          value: summerTerm  # 初始化时创建的用户名称
        - name: MYSQL_PASSWORD
          value: summerTerm  # 初始化时创建的用户密码
        ports:
        - containerPort: 3306  # 容器内部 MySQL 服务的端口
        volumeMounts:
        - name: mysql-persistent-storage  # 挂载的卷名称，用于持久化 MySQL 数据
          mountPath: /var/lib/mysql  # MySQL 数据库在容器中的存储路径
      volumes:
      - name: mysql-persistent-storage  # 定义卷的名称，名称必须与上面的 volumeMounts 对应
        emptyDir: {}  # 使用 emptyDir 卷，这种卷在 Pod 重启时会清空数据，适合开发或测试环境
