# 定义 MySQL 的 Service，用于暴露 MySQL 服务给其他服务访问
apiVersion: v1
kind: Service
metadata:
  name: mysql  # 服务的名称
spec:
  selector:
    app: mysql  # 选择带有此标签的 Pod
  ports:
    - protocol: TCP  # 使用的协议类型，这里是 TCP
      port: 3306  # 服务暴露的端口，供其他服务访问
      targetPort: 3306  # 容器内 MySQL 监听的端口
  type: ClusterIP  # 服务类型为 ClusterIP，表示服务只在集群内部可访问
