spring:
  cloud:
    loadbalancer:
      nacos:
        enabled: true
    sentinel:
      transport:
        dashboard: localhost:8090
      block-page: /blocked

feign:
  sentinel:
    enabled: true
  okhttp:
    enabled: true # 开启OKHttp连接池支持